a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
c=int(input("Enter third number: "))
print("\nBefore swapping:")
print("a =", a, "\nb =", b, "\nc =", c)
print("\nAfter swapping:")
print("a =", a, "\nb =", b, "\nc =", c)